Cast ByteBuffer to Buffer before calling position()
On some devices (e.g ROG Phone) there will be error while patching boot.img:

Caused by: java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)

Signed-off-by: Shaka Huang <shakalaca@gmail.com>